server:
  port: 8081

spring:
  applcation:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.durid.pool.DuridDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lioenix.springcloud.entities